name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '!v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  CreateRelease:
    name: Create Release
    uses: EncoreDigitalGroup/.github/.github/workflows/create-release.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      generate_release_notes: true
      is_draft: false
      pre_release: false
